//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/PlayerInput.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInput: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInput()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInput"",
    ""maps"": [
        {
            ""name"": ""CharacterControls"",
            ""id"": ""dd1a4549-e659-41da-8612-80a0abfe834e"",
            ""actions"": [
                {
                    ""name"": ""Jab"",
                    ""type"": ""Button"",
                    ""id"": ""52ecffe9-a7df-430b-8884-4aae197286fd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Guard"",
                    ""type"": ""Button"",
                    ""id"": ""92473885-d058-4d6f-b14a-d30e534129a4"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightJab"",
                    ""type"": ""Button"",
                    ""id"": ""e309ef1e-f402-4e81-a0e3-fb0f2d21e447"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot"",
                    ""type"": ""Button"",
                    ""id"": ""20ca1b60-f6d8-4e19-a573-e75ee034db5d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftHook"",
                    ""type"": ""Button"",
                    ""id"": ""359e85c4-9576-4e36-885a-0d1819f6ac7b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightHook"",
                    ""type"": ""Button"",
                    ""id"": ""1261beb1-243a-496c-990a-1d453f4ea508"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftUppercut"",
                    ""type"": ""Button"",
                    ""id"": ""ca68b146-0a20-4b96-afb1-da6c0f58ac75"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightUppercut"",
                    ""type"": ""Button"",
                    ""id"": ""4b349b35-c5c3-4738-a231-ba84d3873af7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""3165d3ad-e9d7-4d82-a97e-d70216bc672a"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e7834757-a84a-41a4-8ccc-ecbe245bcdc6"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Guard"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3d73dbe8-5f9b-420a-87bf-0ac9065aaec4"",
                    ""path"": ""<Keyboard>/z"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightJab"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0a55a3d0-7519-4392-9190-efd097027146"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4cb870cc-6a79-4dd2-93ea-79912f19619f"",
                    ""path"": ""<Keyboard>/t"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftHook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""37e7f635-9d86-4ac1-aeda-9488fd88bd15"",
                    ""path"": ""<Keyboard>/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightHook"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6769b8ad-0596-460d-a273-357709ed51c4"",
                    ""path"": ""<Keyboard>/u"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftUppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""250fca60-a4fc-47b3-adb3-29f76aa240c9"",
                    ""path"": ""<Keyboard>/i"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightUppercut"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // CharacterControls
        m_CharacterControls = asset.FindActionMap("CharacterControls", throwIfNotFound: true);
        m_CharacterControls_Jab = m_CharacterControls.FindAction("Jab", throwIfNotFound: true);
        m_CharacterControls_Guard = m_CharacterControls.FindAction("Guard", throwIfNotFound: true);
        m_CharacterControls_RightJab = m_CharacterControls.FindAction("RightJab", throwIfNotFound: true);
        m_CharacterControls_Shoot = m_CharacterControls.FindAction("Shoot", throwIfNotFound: true);
        m_CharacterControls_LeftHook = m_CharacterControls.FindAction("LeftHook", throwIfNotFound: true);
        m_CharacterControls_RightHook = m_CharacterControls.FindAction("RightHook", throwIfNotFound: true);
        m_CharacterControls_LeftUppercut = m_CharacterControls.FindAction("LeftUppercut", throwIfNotFound: true);
        m_CharacterControls_RightUppercut = m_CharacterControls.FindAction("RightUppercut", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // CharacterControls
    private readonly InputActionMap m_CharacterControls;
    private List<ICharacterControlsActions> m_CharacterControlsActionsCallbackInterfaces = new List<ICharacterControlsActions>();
    private readonly InputAction m_CharacterControls_Jab;
    private readonly InputAction m_CharacterControls_Guard;
    private readonly InputAction m_CharacterControls_RightJab;
    private readonly InputAction m_CharacterControls_Shoot;
    private readonly InputAction m_CharacterControls_LeftHook;
    private readonly InputAction m_CharacterControls_RightHook;
    private readonly InputAction m_CharacterControls_LeftUppercut;
    private readonly InputAction m_CharacterControls_RightUppercut;
    public struct CharacterControlsActions
    {
        private @PlayerInput m_Wrapper;
        public CharacterControlsActions(@PlayerInput wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jab => m_Wrapper.m_CharacterControls_Jab;
        public InputAction @Guard => m_Wrapper.m_CharacterControls_Guard;
        public InputAction @RightJab => m_Wrapper.m_CharacterControls_RightJab;
        public InputAction @Shoot => m_Wrapper.m_CharacterControls_Shoot;
        public InputAction @LeftHook => m_Wrapper.m_CharacterControls_LeftHook;
        public InputAction @RightHook => m_Wrapper.m_CharacterControls_RightHook;
        public InputAction @LeftUppercut => m_Wrapper.m_CharacterControls_LeftUppercut;
        public InputAction @RightUppercut => m_Wrapper.m_CharacterControls_RightUppercut;
        public InputActionMap Get() { return m_Wrapper.m_CharacterControls; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(CharacterControlsActions set) { return set.Get(); }
        public void AddCallbacks(ICharacterControlsActions instance)
        {
            if (instance == null || m_Wrapper.m_CharacterControlsActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_CharacterControlsActionsCallbackInterfaces.Add(instance);
            @Jab.started += instance.OnJab;
            @Jab.performed += instance.OnJab;
            @Jab.canceled += instance.OnJab;
            @Guard.started += instance.OnGuard;
            @Guard.performed += instance.OnGuard;
            @Guard.canceled += instance.OnGuard;
            @RightJab.started += instance.OnRightJab;
            @RightJab.performed += instance.OnRightJab;
            @RightJab.canceled += instance.OnRightJab;
            @Shoot.started += instance.OnShoot;
            @Shoot.performed += instance.OnShoot;
            @Shoot.canceled += instance.OnShoot;
            @LeftHook.started += instance.OnLeftHook;
            @LeftHook.performed += instance.OnLeftHook;
            @LeftHook.canceled += instance.OnLeftHook;
            @RightHook.started += instance.OnRightHook;
            @RightHook.performed += instance.OnRightHook;
            @RightHook.canceled += instance.OnRightHook;
            @LeftUppercut.started += instance.OnLeftUppercut;
            @LeftUppercut.performed += instance.OnLeftUppercut;
            @LeftUppercut.canceled += instance.OnLeftUppercut;
            @RightUppercut.started += instance.OnRightUppercut;
            @RightUppercut.performed += instance.OnRightUppercut;
            @RightUppercut.canceled += instance.OnRightUppercut;
        }

        private void UnregisterCallbacks(ICharacterControlsActions instance)
        {
            @Jab.started -= instance.OnJab;
            @Jab.performed -= instance.OnJab;
            @Jab.canceled -= instance.OnJab;
            @Guard.started -= instance.OnGuard;
            @Guard.performed -= instance.OnGuard;
            @Guard.canceled -= instance.OnGuard;
            @RightJab.started -= instance.OnRightJab;
            @RightJab.performed -= instance.OnRightJab;
            @RightJab.canceled -= instance.OnRightJab;
            @Shoot.started -= instance.OnShoot;
            @Shoot.performed -= instance.OnShoot;
            @Shoot.canceled -= instance.OnShoot;
            @LeftHook.started -= instance.OnLeftHook;
            @LeftHook.performed -= instance.OnLeftHook;
            @LeftHook.canceled -= instance.OnLeftHook;
            @RightHook.started -= instance.OnRightHook;
            @RightHook.performed -= instance.OnRightHook;
            @RightHook.canceled -= instance.OnRightHook;
            @LeftUppercut.started -= instance.OnLeftUppercut;
            @LeftUppercut.performed -= instance.OnLeftUppercut;
            @LeftUppercut.canceled -= instance.OnLeftUppercut;
            @RightUppercut.started -= instance.OnRightUppercut;
            @RightUppercut.performed -= instance.OnRightUppercut;
            @RightUppercut.canceled -= instance.OnRightUppercut;
        }

        public void RemoveCallbacks(ICharacterControlsActions instance)
        {
            if (m_Wrapper.m_CharacterControlsActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(ICharacterControlsActions instance)
        {
            foreach (var item in m_Wrapper.m_CharacterControlsActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_CharacterControlsActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public CharacterControlsActions @CharacterControls => new CharacterControlsActions(this);
    public interface ICharacterControlsActions
    {
        void OnJab(InputAction.CallbackContext context);
        void OnGuard(InputAction.CallbackContext context);
        void OnRightJab(InputAction.CallbackContext context);
        void OnShoot(InputAction.CallbackContext context);
        void OnLeftHook(InputAction.CallbackContext context);
        void OnRightHook(InputAction.CallbackContext context);
        void OnLeftUppercut(InputAction.CallbackContext context);
        void OnRightUppercut(InputAction.CallbackContext context);
    }
}
